### PR TITLE
Merge develop to discvr-20.11

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Review by labkey-adam — COMMENTED** [review]
@bbimber These two dependencies.txt files should not be committed; these will cause merge conflicts for anyone who builds and pulls this code.

**Comment by bbimber** [comment]
@labkey-adam i had a conversation a while back about checking in these files with some combination of josh/trey/susan in the past. as you might see, i have been checking in dependencies.txt for my modules. I realize it isnt necessary, but my rationale had been that they serve a function vaguely like package lock files, in that when dependencies bump, they update, giving a warning that I need to update jars.txt. In those conversations merge issues never came up. Are you talking about committing dependencies.txt in general, or a specific problem with the commit/merge pattern on these two files?

If you dont want dependencies.txt committed that's fine - just trying to understand this.

**Comment by labkey-adam** [comment]
All I know is that my build produced versions of these files and IntelliJ's "git pull" action (which does a shelf and restore) then blocked the pull on this repo due to "uncommitted file conflicts." I thought maybe your commit was unintentional, but since not, I think we can leave this as is. I see that they were merged (to the fork) fairly recently, so next time I'll bet IntelliJ will be happier.

In short: never mind...

**Comment by bbimber** [comment]
OK - if i'm doing something improper in my merge process I'm happy to adjust or watch for it. i had to script most of my merging since managing multiple repos and the bimberlab*/labkey merge is not simple.

**Comment by bbimber** [comment]
two more things;

- should this file pattern be put into .gitignore then?

- have you guys considered whether jars.txt needs to exist? it just seems silly to manually maintain it. doesnt gradle know what version of the artifact it has and some metadata about them?

**Comment by labkey-adam** [comment]
I think a .gitignore file is used to specify intentionally untracked files. Since these dependency.txt files are tracked, .gitignore won't do anything.

We've discussed altering the credits process. We'll likely maintain a slimmed down jars.txt (to document purpose, owner, etc.) but we agree that, in theory, the version number should be filled in automatically. Josh & Susan have looked at making this change, but it's apparently more complicated than you might think. It's also, frankly, not the highest priority thing to fix at the moment.

**Comment by bbimber** [comment]
Yeah I get that git ignore is moot once the file is tracked, but if labkeys position is that we should not track dependencies.txt, would it make sense to add this pattern to gitignore? 

I completely understand credits is tough to prioritize.

**Pull request merged**
